// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://impbefoxbakhanpehkbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcGJlZm94YmFraGFucGVoa2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDU0MDMsImV4cCI6MjA2Mzc4MTQwM30.9eCoEhZZofBDPHPPn32w0L3IjWj0fpMrFvawWDPVjAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);